### ISSUE TITLE
problems with initial usage

### ISSUE THREAD

**Issue by LauraSkak** [snajder-r/MetH5Format#4]
Hey

I downloaded meth5 using conda. I'm getting the following error, when i'm using the software.

Traceback (most recent call last):
  File "/home/lask/miniconda3/envs/meth5/bin/meth5", line 6, in <module>
    from meth5.__main__ import main
  File "/home/lask/miniconda3/envs/meth5/lib/python3.12/site-packages/meth5/__main__.py", line 4, in <module>
    from meth5.meth5 import MetH5File
  File "/home/lask/miniconda3/envs/meth5/lib/python3.12/site-packages/meth5/meth5.py", line 10, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/home/lask/miniconda3/envs/meth5/lib/python3.12/collections/__init__.py)

Is there some missing dependancies?

**Comment by snajder-r** [comment]
Hi @LauraSkak,

It looks like python3.10 made changes to the Collections library. I had only tested the MetH5 package with python 3.7 and 3.8 and had hoped it would be a while before dependencies break, so I left the upper-end open in the package definition.

As a quick workaround, try

    conda install python=3.9

Best,
Rene

**Comment by LauraSkak** [comment]
Thank you so much for the quick respons! :)

**Comment by LauraSkak** [comment]
now it says this;

Traceback (most recent call last):
  File "/home/lask/miniconda3/envs/pycometh/bin/meth5", line 6, in <module>
    from meth5.__main__ import main
  File "/home/lask/miniconda3/envs/pycometh/lib/python3.9/site-packages/meth5/__main__.py", line 5, in <module>
    import meth5.main_create_m5
  File "/home/lask/miniconda3/envs/pycometh/lib/python3.9/site-packages/meth5/main_create_m5.py", line 3, in <module>
    import tqdm
ModuleNotFoundError: No module named 'tqdm'

**Comment by snajder-r** [comment]
Weird, tqdm is a dependency that should be automatically installed with MetH5. 

Please either try installing it manually with

    conda install tqdm

or perhaps start from scratch. Create a new conda environment and then install

conda install -c snajder-r meth5 python=3.9

**Comment by snajder-r** [comment]
Now that I got around to testing it myself, it seems python 3.8 works more reliably. So if you have issues installing it with python 3.9, try python 3.8.

**Comment by SanVerb** [comment]
Hello

I also seem to have troubles with initial usage:

I created a new conda environment and then installed meth5 via:  `conda install -c snajder-r meth5`

conda list gives as output:
![image](https://github.com/PMBio/MetH5Format/assets/119843490/4008ed4d-3136-4f29-bd42-41a53e998cbe)

but then: `meth5 -h` shows the following:
![image](https://github.com/PMBio/MetH5Format/assets/119843490/2273073d-fc30-475d-8cf0-c3a112124e9c)

I'm not really sure what I missed.

(pip install meth5 does not work for me: "ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects"

Kind regards

Sanché Verbeeck

**Comment by mpodio81** [comment]
Hi,
Im trying to run I can not. I installed it (incorporated all the Module that was needed). But It is not running. I dont receive any error but it doesn't generate a .m5 file.

Kind regards, Maricel

**Comment by ChloeL2023** [comment]
Hi @snajder-r ,
I also encountered the same error although I install with python3.9:
(meth5) [root@localhost work]# meth5                                                                            
Traceback (most recent call last):                                                                              
  File "/root/miniconda3/envs/meth5/bin/meth5", line 6, in <module>                                             
    from meth5.__main__ import main                                                                             
ModuleNotFoundError: No module named 'meth5'

pip also invalid for me. Could you help with this issue? Thanks!

Best regards,
Chloe
